repos:
  - repo: https://github.com/charliermarsh/ruff
    rev: stable
    hooks:
      - id: ruff
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: stable
    hooks:
      - id: isort
